name: sklearn
dependencies:
- python=3.7
- pip:
  - mxnet==1.5.0
  - d2lzh==0.8.11
  - jupyter==1.0.0
  - numpy==1.17.2
  - scipy==1.3.1
  - pandas==0.25.2
  - scikit-learn==0.21.3
  - matplotlib==2.2.2
  - pydotplus==2.0.2
